### ISSUE TITLE
Remove Vish's e-mail address in READEME.md

### ISSUE THREAD

**Issue by yumaoka** [IBM-Cloud/gp-ruby-sample#1]
Vish's e-mail address is included in README.md. The e-mail address no longer works. We also don't need to have the e-mail contact there.

**Comment by pgaglani1** [comment]
[Pull request](https://github.com/IBM-Bluemix/gp-ruby-sample/pull/2) for this fix

**Comment by srl295** [comment]
Fixed in #2
